"""updated primary key track

Revision ID: 1edc6ffabbc0
Revises: 
Create Date: 2025-01-03 14:36:28.978329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edc6ffabbc0'
down_revision = None
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('track', 'track_backup')

    # Step 2: Create the new table
    op.create_table(
       'track',
       sa.Column('id', sa.Integer(), primary_key=True),
       sa.Column('track_id', sa.String(length=100), nullable=False),
       sa.Column('name', sa.String(100), nullable=False),
       sa.Column('artist', sa.String(100), nullable=False),
       sa.Column('danceability', sa.Float),
       sa.Column('energy', sa.Float),
       sa.Column('key', sa.Float),
       sa.Column('loudness', sa.Float),
       sa.Column('mode', sa.Float),
       sa.Column('speechiness', sa.Float),
       sa.Column('acousticness', sa.Float),
       sa.Column('instrumentalness', sa.Float),
       sa.Column('liveness', sa.Float),
       sa.Column('valence', sa.Float),
       sa.Column('tempo', sa.Float),
       sa.Column('artist_id', sa.String(), sa.ForeignKey('artist.artist_id'), nullable=False)
    )

    op.execute('INSERT INTO track SELECT id, track_id, name, artist, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, artist_id FROM track_backup')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
