"""updated auto_increment track

Revision ID: b153a7a27458
Revises: 1edc6ffabbc0
Create Date: 2025-01-03 14:44:31.666238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b153a7a27458'
down_revision = '1edc6ffabbc0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_track')
    op.rename_table('track', 'track_backup2')

    # Step 2: Create the new table
    op.create_table(
       'track',
       sa.Column('id', sa.Integer(), primary_key=True),
       sa.Column('track_id', sa.String(length=100), nullable=False),
       sa.Column('name', sa.String(100), nullable=False),
       sa.Column('artist', sa.String(100), nullable=False),
       sa.Column('danceability', sa.Float),
       sa.Column('energy', sa.Float),
       sa.Column('key', sa.Float),
       sa.Column('loudness', sa.Float),
       sa.Column('mode', sa.Float),
       sa.Column('speechiness', sa.Float),
       sa.Column('acousticness', sa.Float),
       sa.Column('instrumentalness', sa.Float),
       sa.Column('liveness', sa.Float),
       sa.Column('valence', sa.Float),
       sa.Column('tempo', sa.Float),
       sa.Column('artist_id', sa.String(), sa.ForeignKey('artist.artist_id'), nullable=False),
       sa.PrimaryKeyConstraint('id')
    )

    op.execute('INSERT INTO track SELECT id, track_id, name, artist, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, artist_id FROM track_backup2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'track_backup', ['track_id'], ['track_id'])

    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('track_backup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=100), nullable=False),
    sa.Column('danceability', sa.FLOAT(), nullable=True),
    sa.Column('energy', sa.FLOAT(), nullable=True),
    sa.Column('key', sa.FLOAT(), nullable=True),
    sa.Column('loudness', sa.FLOAT(), nullable=True),
    sa.Column('mode', sa.FLOAT(), nullable=True),
    sa.Column('speechiness', sa.FLOAT(), nullable=True),
    sa.Column('acousticness', sa.FLOAT(), nullable=True),
    sa.Column('instrumentalness', sa.FLOAT(), nullable=True),
    sa.Column('liveness', sa.FLOAT(), nullable=True),
    sa.Column('valence', sa.FLOAT(), nullable=True),
    sa.Column('tempo', sa.FLOAT(), nullable=True),
    sa.Column('artist_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], name='fk_track_artist_id_artist')
    )
    # ### end Alembic commands ###
